# Generated by Django 5.2.10 on 2026-04-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255, null=True)),
                ('fee', models.FloatField(default=0)),
                ('tracking_number', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('shipped_at', models.DateTimeField(null=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='orders.order')),
            ],
            options={
                'db_table': 'shipping',
            },
        ),
    ]
