# Generated by Django 5.2.10 on 2026-04-27 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('staff_id', models.IntegerField(null=True)),
                ('coupon_code', models.CharField(max_length=255, null=True)),
                ('total_price', models.FloatField()),
                ('total_quantity', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(null=True)),
                ('saga_status', models.CharField(default='INITIATED', max_length=255)),
                ('saga_step', models.CharField(max_length=255, null=True)),
                ('saga_error', models.TextField(null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
